view: products {
  sql_table_name: `lookercoredemoangiephenn.trial_dataset.products` ;;
  drill_fields: [id]

  dimension: id {
    primary_key: yes
    type: number
    sql: ${TABLE}.id ;;
  }
  dimension: brand {
    type: string
    sql: ${TABLE}.brand ;;
    ### extended by link
    link: {
      label: "Brand Lookup"
      url: "http://www.google.com/search?q={{ value }}"###dynamically adds the brand name to end of URL###
      icon_url: "http://google.com/favicon.ico" ###Google logo will be displayed for this link###
    }
  }

  dimension: category {
    type: string
    sql: ${TABLE}.category ;;
    description: "AHHHHHHH"
  }
  dimension: cost {
    type: number
    sql: ${TABLE}.cost ;;
  }
  dimension: department {
    type: string
    sql: ${TABLE}.department ;;
  }
  dimension: distribution_center_id {
    type: number
    # hidden: yes
    sql: ${TABLE}.distribution_center_id ;;
  }
  dimension: name {
    type: string
    sql: ${TABLE}.name ;;
  }
  dimension: retail_price {
    type: number
    sql: ${TABLE}.retail_price ;;
  }

  dimension: sku {
    label: "Stock ID"
    type: string
    sql: ${TABLE}.sku ;;
    description: " 'Stock Keeping Unit"
  }
  measure: count {
    label: "Total Products"
    type: count
    drill_fields: [detail*]
    description: "Total number of Products"
  }

  ###CUSTOM DIMENSIONS###
  #dimension: category_icon {
    #type:  string
    #sql:
    #CASE
    #WHEN ${category} = 'Intimates' THEN '🩲'
    #WHEN ${category} = 'Jeans' THEN '👖'
    #WHEN ${category} = 'Tops & Tees' THEN '👕'
    #WHEN ${category} = 'Fashion Hoodies & Sweatshirts' THEN '💦'
    #WHEN ${category} = 'Swim' THEN '🏊'
    #WHEN ${category} = 'Shorts' THEN '🩳'
    #WHEN ${category} = 'Sleep & Lounge' THEN '😴'
    #WHEN ${category} = 'Sweaters' THEN '💧'
    #WHEN ${category} = 'Accessories' THEN '🎀'
    #WHEN ${category} = 'Active' THEN '🏋'
    #WHEN ${category} = 'Outerwear & Coats' THEN '🧥'
    #WHEN ${category} = 'Underwear' THEN '👙'
    #WHEN ${category} = 'Pants' THEN '🧍'
    #WHEN ${category} = 'Socks' THEN '🧦'
    #WHEN ${category} = 'Dresses' THEN '👗'
    #WHEN ${category} = 'Maternity' THEN '🫄'
    #WHEN ${category} = 'Suits & Sport Coats' THEN '🏅'
    #WHEN ${category} = 'Plus' THEN '➕'
    #WHEN ${category} = 'Socks & Hosiery' THEN '👟'
    #WHEN ${category} = 'Pants & Capris' THEN '⛱'
    #WHEN ${category} = 'Blazers & Jackets' THEN '🌆'
    #WHEN ${category} = 'Leggings' THEN '🦵'
    #WHEN ${category} = 'Skirts' THEN '🥻'
    #WHEN ${category} = 'Suits' THEN '🕴'
    #WHEN ${category} = 'Jumpsuits & Rompers' THEN '🦘'
    #WHEN ${category} = 'Clothing Sets' THEN '📐'
    #ELSE ❗
    #END;;
  #}

  ###CUSTOM MEASURES###
  measure: total_cost {
    label: "Total Product Costs"
    type: sum
    sql: ${cost} ;;
    description: "Total Costs generated by products"
    }

  measure: average_cost {
    label: "AVG Product Costs"
    type: average
    sql: ${cost} ;;
    description: "Average costs generated by products"
    }

  measure: total_retail_price{
    label: "Total Retail Price"
    type: sum
    sql: ${retail_price} ;;
    description: "Baseline price before discounts and promotions etc"
  }

  ####DB Test#####
  dimension: concat_Cat_Dep {
    label: "Test"
    type: string
    sql:CONCAT(${category},'|',${department}  ;;
    }

  # ----- Sets of fields for drilling ------
  set: detail {
    fields: [
  id,
  name,
  distribution_centers.name,
  distribution_centers.id,
  order_items.count,
  inventory_items.count
  ]
  }

}
